services:
  - type: web
    name: savitur-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./web-app/backend/Dockerfile
    dockerContext: .
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        value: https://savitur.vercel.app,https://savitur-git-master-loki98s-projects.vercel.app,https://savitur-ns7vbkn6f-loki98s-projects.vercel.app

